const ActionTypes = {
    LOADER: 'LOADER',
    SHOWERROR: 'SHOWERROR',
    SORTEDPR: 'SORTEDPR',
    HIDEERROR: 'HIDEERROR',
    POSTJOBS: 'POSTJOBS',
    ALLJOBS: 'ALLJOBS',
    JOBKEYS: 'JOBKEYS',
    ALLREPORTS: 'ALLREPORTS',
    ALLJOBKEYS: 'ALLJOBKEYS',
    REPORTJOBKEYS: 'ALLJOBKEYS',
    PREREGISTRATION: 'PREREGISTRATION',
    ALLPREREGISTRATION: 'ALLPREREGISTRATION',
    INDEX: 'INDEX',
    SETDEFDROPDOWNOPTIONS: 'SETDEFDROPDOWNOPTIONS',
    SELECTEDJOB:'SELECTEDJOB',
    PRADDIONALDATA:'PRADDIONALDATA'
}

export default ActionTypes;
